# Generated by Django 3.1.7 on 2021-03-06 06:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='department_name')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='registerd_date')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=20, verbose_name='last_name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='registerd_date')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.department', verbose_name='department')),
            ],
        ),
    ]
